# Generated by Django 5.0.7 on 2024-07-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_subjects',
            field=models.ManyToManyField(to='tutors.subject'),
        ),
    ]
